name: cadastro_empresa
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  path: ^1.8.0
  uuid: 3.0.6
  http: ^0.13.5
  brasil_fields: 1.4.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
